# Generated by Django 4.0.5 on 2022-07-27 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('idcte', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedrif', models.CharField(max_length=75, verbose_name='Cedula o Rif')),
                ('nombre', models.CharField(max_length=75, verbose_name='Nombre')),
                ('direccion', models.CharField(max_length=75, verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=75, verbose_name='Teléfono')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('idprov', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedrif', models.CharField(max_length=75, verbose_name='Cedula o Rif')),
                ('nombre', models.CharField(max_length=75, verbose_name='Nombre')),
                ('direccion', models.CharField(max_length=75, verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=75, verbose_name='Teléfono')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'proveedores',
            },
        ),
        migrations.CreateModel(
            name='Requerimientos',
            fields=[
                ('idreq', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=75, verbose_name='Nombre')),
                ('tipo', models.IntegerField(choices=[(1, 'Foto'), (2, 'Video'), (3, 'Plano')], default=1, verbose_name='Tipo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Actualizado')),
                ('idcte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppRequerimientos.clientes', verbose_name='ID Cliente')),
                ('idprov', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppRequerimientos.proveedores', verbose_name='ID Proveedor')),
            ],
            options={
                'verbose_name': 'Requerimiento',
                'verbose_name_plural': 'Requerimientos',
                'db_table': 'requerimientos',
            },
        ),
    ]
